/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dPRrTyFHK7W9ZJqYsJHqzM

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsvGhBehH8Uupx } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: V_GhBehH8UUPX/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsvGhBehH8Uupx
});
