/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dPRrTyFHK7W9ZJqYsJHqzM

import * as React from "react";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: dPRrTyFHK7W9ZJqYsJHqzM/projectModule
import { CmsCredentialsProvider } from "@plasmicpkgs/plasmic-cms";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  cmsCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof CmsCredentialsProvider>, "children">
  >;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, cmsCredentialsProviderProps, embedCssProps } = props;

  return (
    <CmsCredentialsProvider
      {...cmsCredentialsProviderProps}
      databaseId={
        cmsCredentialsProviderProps &&
        "databaseId" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseId!
          : "85dpYGc3kRURUVyhhDpHiH"
      }
      databaseToken={
        cmsCredentialsProviderProps &&
        "databaseToken" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseToken!
          : "uJpVBDclEXSpE7Eldb3DycRN5Y3AOX4SXg6zZQP7zGtMhLfvbW69CnOkIIfb5PfI9qPOaJeECisBPlVMPiEEA"
      }
      host={
        cmsCredentialsProviderProps && "host" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.host!
          : "https://data.plasmic.app"
      }
      locale={
        cmsCredentialsProviderProps && "locale" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.locale!
          : undefined
      }
    >
      <EmbedCss
        {...embedCssProps}
        css={
          embedCssProps && "css" in embedCssProps
            ? embedCssProps.css!
            : "body {\r\n  margin: 0;\r\n}\r\n.stack-grid {\r\n  display: grid;\r\n  place-items: center;\r\n  isolation: isolate;\r\n}\r\n.stack-grid > * {\r\n  grid-column: 1/-1;\r\n  grid-row: 1/-1;\r\n}\r\n.stack-grid-media {\r\n  z-index: -1;\r\n}\r\n\r\n@keyframes rotate {\r\n    0% {\r\n      opacity: 0;\r\n    }\r\n    \r\n    20%, 80% {\r\n      opacity: 1;\r\n    }\r\n    \r\n    100% {\r\n      opacity: 0;\r\n    }\r\n  }\r\n\r\n.text-carousel .__wab_flex-container h1:nth-child(1) {\r\n  animation: rotate 1.5s 0 forwards;\r\n}\r\n.text-carousel .__wab_flex-container h1:nth-child(2) {\r\n  animation: rotate 1.5s 3s forwards;\r\n}\r\n.text-carousel .__wab_flex-container h1:nth-child(3) {\r\n  animation: rotate 1.5s 6s forwards;\r\n}\r\n.text-carousel .__wab_flex-container h1:nth-child(4) {\r\n  animation: rotate 1.5s 9s forwards;\r\n}\r\n.text-carousel .__wab_flex-container h1:nth-child(5) {\r\n  animation: rotate 1.5s 12s forwards;\r\n}\r\n.text-carousel .__wab_flex-container h1:nth-child(6) {\r\n  animation: rotate 1.5s 15s forwards;\r\n}\r\n.text-carousel .__wab_flex-container h1:nth-child(7) {\r\n  animation: rotate 1.5s 18s forwards;\r\n}\r\n"
        }
      >
        {children}
      </EmbedCss>
    </CmsCredentialsProvider>
  );
}
