/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dPRrTyFHK7W9ZJqYsJHqzM
// Component: l--2YaZ18sjM

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Button from "../../Button"; // plasmic-import: XxpXfQpfq__Y/component
import { HelloWorld } from "~/components/HelloWorld"; // plasmic-import: -276YMIT3j/codeComponent
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: dPRrTyFHK7W9ZJqYsJHqzM/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: dPRrTyFHK7W9ZJqYsJHqzM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_pracitce_oyster_bay.module.css"; // plasmic-import: dPRrTyFHK7W9ZJqYsJHqzM/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: l--2YaZ18sjM/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: QOcwsJ1FCjFi/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: iRLbodS886l/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: QLAS9aiAy6p/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: VTAAmSXa7QY/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: 4E1S_Vn3o6p/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  helloWorld?: Flex__<typeof HelloWorld>;
  footer?: Flex__<"div">;
  columns?: Flex__<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

const $$ = {};

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__etbPj)}>
            <div className={classNames(projectcss.all, sty.freeBox__ycd99)}>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__sowYs
                )}
                href={`/`}
                platform={"react"}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__tq1Kx)}
                  displayHeight={"40px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"40px"}
                  src={{
                    src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMCAxMCI+CiAgPHJlY3Qgd2lkdGg9IjEwIiBoZWlnaHQ9IjEwIiByeD0iMyIgZmlsbD0iIzA1MDUwNSIvPgogIDxyZWN0IHg9IjEuNSIgeT0iNSIgd2lkdGg9IjMiIGhlaWdodD0iMyIgcng9Ii4yNSIgZmlsbD0iI2ZmZiIvPgogIDxyZWN0IHg9IjUuNSIgeT0iNSIgd2lkdGg9IjMiIGhlaWdodD0iMyIgcng9IjEuNSIgZmlsbD0iI2ZmZiIvPgogIDxwYXRoIGQ9Ik00LjY1NCAxLjZjLjExMy0uMTk3LjE3LS4yOTUuMjQ0LS4zMjhhLjI1LjI1IDAgMDEuMjA0IDBjLjA3NC4wMzMuMTMuMTMxLjI0NC4zMjhsMS4wNCAxLjhjLjExMy4xOTcuMTcuMjk1LjE2Mi4zNzZhLjI1LjI1IDAgMDEtLjEwMi4xNzZDNi4zOCA0IDYuMjY2IDQgNi4wMzkgNEgzLjk2MWMtLjIyOCAwLS4zNDEgMC0uNDA3LS4wNDhhLjI1LjI1IDAgMDEtLjEwMi0uMTc2Yy0uMDA4LS4wOC4wNDktLjE4LjE2Mi0uMzc2bDEuMDQtMS44eiIgZmlsbD0iI2ZmZiIvPgo8L3N2Zz4K",
                    fullWidth: 150,
                    fullHeight: 150,
                    aspectRatio: 1
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bmC1V
                  )}
                >
                  {"Practice"}
                </div>
              </PlasmicLink__>
              <div className={classNames(projectcss.all, sty.freeBox__vulJ)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__ulJte
                  )}
                  href={`/schedule`}
                  platform={"react"}
                >
                  {"Schedule"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__oiy8F
                  )}
                  href={`/about`}
                  platform={"react"}
                >
                  {"About"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___2V2SF
                  )}
                  href={`/about`}
                  platform={"react"}
                >
                  {"Offerings"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__hcAi2
                  )}
                  href={"https://www.plasmic.app/"}
                  platform={"react"}
                >
                  {"Pricing"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__vZbze
                  )}
                  href={"https://www.plasmic.app/"}
                  platform={"react"}
                >
                  {"Deals & Events"}
                </PlasmicLink__>
              </div>
              {false ? (
                <div className={classNames(projectcss.all, sty.freeBox__qy1F2)}>
                  <button
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button__xpPC
                    )}
                  >
                    {"Sign up"}
                  </button>
                  <Button
                    className={classNames("__wab_instance", sty.button__aaynv)}
                    color={"clear"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__gjEjl)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__vBfln)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tgxn3
                      )}
                    >
                      {"Log in"}
                    </div>
                  </Button>
                </div>
              ) : null}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__jukLq)}>
              <div className={classNames(projectcss.all, sty.freeBox__maRnk)}>
                <div
                  className={classNames(
                    projectcss.all,
                    sty.freeBox__oslnU,
                    "text-carousel"
                  )}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__veKwC
                    )}
                  >
                    {"Yoga"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__be0Xx
                    )}
                  >
                    {"Pilates"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___5MFgE
                    )}
                  >
                    {"Alignment"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___4ZCC
                    )}
                  >
                    {"Strength"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__qeJ7
                    )}
                  >
                    {"Connection"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___6XXRb
                    )}
                  >
                    {"Digestion"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__vgyKz
                    )}
                  >
                    {"Mental Clarity"}
                  </h1>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__bfCdm)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__qdLlT)}
                    color={"green"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__n15Az)}
                        role={"img"}
                      />
                    }
                    onClick={async event => {
                      const $steps = {};
                    }}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg___87Tqh)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__r0BI2
                      )}
                    >
                      {"Start now ->"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__yhNtC)}
                    color={"green"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__ow3JX)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg___2Drxo)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aqQg
                      )}
                    >
                      {"Learn more\u2026"}
                    </div>
                  </Button>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__uLi4O)}>
              <div className={classNames(projectcss.all, sty.freeBox__zUbXq)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5EuMd
                  )}
                >
                  {"Let's get moving."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lHoRd
                  )}
                >
                  {
                    "Orci dui condimentum rutrum laoreet hac purus porta sem sem a vivamus a posuere vel molestie. Yada Yad..."
                  }
                </div>
                <Button
                  className={classNames("__wab_instance", sty.button__mu9Y6)}
                  color={"green"}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg__xwDne)}
                      role={"img"}
                    />
                  }
                  onClick={async event => {
                    const $steps = {};

                    $steps["runCode"] = true
                      ? (() => {
                          const actionArgs = {
                            customFunction: async () => {
                              return (() => {
                                return alert("this  button was clicked");
                              })();
                            }
                          };
                          return (({ customFunction }) => {
                            return customFunction();
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runCode"] != null &&
                      typeof $steps["runCode"] === "object" &&
                      typeof $steps["runCode"].then === "function"
                    ) {
                      $steps["runCode"] = await $steps["runCode"];
                    }

                    $steps["updateStateVariable"] = true
                      ? (() => {
                          const actionArgs = {};
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;
                            undefined;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateStateVariable"] != null &&
                      typeof $steps["updateStateVariable"] === "object" &&
                      typeof $steps["updateStateVariable"].then === "function"
                    ) {
                      $steps["updateStateVariable"] = await $steps[
                        "updateStateVariable"
                      ];
                    }
                  }}
                  startIcon={
                    <CheckSvgIcon
                      className={classNames(projectcss.all, sty.svg__aykkr)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bo7Oh
                    )}
                  >
                    {"Start now ->"}
                  </div>
                </Button>
              </div>
            </div>
            <HelloWorld
              data-plasmic-name={"helloWorld"}
              data-plasmic-override={overrides.helloWorld}
              children={null}
              className={classNames("__wab_instance", sty.helloWorld)}
              verbose={true}
            />

            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column___3Ki4H)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vhq2T)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__m8Evg)}
                      displayHeight={"40px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"40px"}
                      src={{
                        src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMCAxMCI+CiAgPHJlY3Qgd2lkdGg9IjEwIiBoZWlnaHQ9IjEwIiByeD0iMyIgZmlsbD0iIzA1MDUwNSIvPgogIDxyZWN0IHg9IjEuNSIgeT0iNSIgd2lkdGg9IjMiIGhlaWdodD0iMyIgcng9Ii4yNSIgZmlsbD0iI2ZmZiIvPgogIDxyZWN0IHg9IjUuNSIgeT0iNSIgd2lkdGg9IjMiIGhlaWdodD0iMyIgcng9IjEuNSIgZmlsbD0iI2ZmZiIvPgogIDxwYXRoIGQ9Ik00LjY1NCAxLjZjLjExMy0uMTk3LjE3LS4yOTUuMjQ0LS4zMjhhLjI1LjI1IDAgMDEuMjA0IDBjLjA3NC4wMzMuMTMuMTMxLjI0NC4zMjhsMS4wNCAxLjhjLjExMy4xOTcuMTcuMjk1LjE2Mi4zNzZhLjI1LjI1IDAgMDEtLjEwMi4xNzZDNi4zOCA0IDYuMjY2IDQgNi4wMzkgNEgzLjk2MWMtLjIyOCAwLS4zNDEgMC0uNDA3LS4wNDhhLjI1LjI1IDAgMDEtLjEwMi0uMTc2Yy0uMDA4LS4wOC4wNDktLjE4LjE2Mi0uMzc2bDEuMDQtMS44eiIgZmlsbD0iI2ZmZiIvPgo8L3N2Zz4K",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__y3M22)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mKp1V
                        )}
                      >
                        {"Connect with us"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wOnx
                        )}
                      >
                        <Icon4Icon
                          className={classNames(projectcss.all, sty.svg__lI8R7)}
                          role={"img"}
                        />

                        <Icon5Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___1TkVj
                          )}
                          role={"img"}
                        />

                        <Icon28Icon
                          className={classNames(projectcss.all, sty.svg__wxm0Z)}
                          role={"img"}
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__pnCe)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mxPhF
                    )}
                  >
                    {
                      "132 South St, Oyster Bay, NY 11771\n1-516-922-2800\ninfo@PracticeOysterBay.com\n\nFAQs  Policies"
                    }
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "helloWorld", "footer", "columns"],
  helloWorld: ["helloWorld"],
  footer: ["footer", "columns"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  helloWorld: typeof HelloWorld;
  footer: "div";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "dPRrTyFHK7W9ZJqYsJHqzM"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    helloWorld: makeNodeComponent("helloWorld"),
    footer: makeNodeComponent("footer"),
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
